apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AutomountServiceAccountToken
metadata:
  name: enforce-automountserviceaccounttoken
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludedNamespaces:
      - "openshift-*"
      - "kube-system"
      - "default"
      - "platform-*"
