apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: automountserviceaccounttoken
  annotations:
    metadata.gatekeeper.sh/title: "Enforce automountServiceAccountToken for Pods"
    metadata.gatekeeper.sh/version: 1.0.1
    description: >-
      Ensures that automountServiceAccountToken is explicitly set to false for Pods in approved namespaces, excluding platform and app namespaces.
spec:
  crd:
    spec:
      names:
        kind: AutomountServiceAccountToken
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            excludePlatformNamespace:
              description: List of platform namespaces to exclude from enforcement
              type: array
              items:
                type: string
            excludeAppNamespace:
              description: List of app namespaces to exclude from enforcement
              type: array
              items:
                type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package automountserviceaccounttoken

        violation[{"msg": msg}] {
          input.review.object.kind == "Pod"
          namespace := input.review.object.metadata.namespace

          # Skip enforcement for platform namespaces
          not namespace_excluded(namespace, input.parameters.excludePlatformNamespace)

          # Skip enforcement for app namespaces
          not namespace_excluded(namespace, input.parameters.excludeAppNamespace)

          # Enforce automountServiceAccountToken to be explicitly set to false
          not input.review.object.spec.automountServiceAccountToken == false

          msg := sprintf("Pod %s in namespace %s must have automountServiceAccountToken set to false", [input.review.object.metadata.name, namespace])
        }

        # Helper function to check if a namespace is excluded
        namespace_excluded(namespace, excludedNamespaces) {
          namespace == excludedNamespaces[_]
        }
