apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: automountserviceaccounttoken
spec:
  crd:
    spec:
      names:
        kind: AutomountServiceAccountToken
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package automountserviceaccounttoken

        violation[{"msg": msg}] {
          input.review.object.kind == "Pod"
          input.review.object.metadata.namespace != ""

          namespace = input.review.object.metadata.namespace

          # Exclude namespaces provided in the parameters
          not namespace_excluded(namespace, input.parameters.excludedNamespaces)

          # Allow exceptions for pods with specific labels or annotations
          not allowed_pod(input.review.object.metadata.labels, input.review.object.metadata.annotations)

          # Check if automountServiceAccountToken is not explicitly set to false
          not input.review.object.spec.automountServiceAccountToken == false

          msg := sprintf("Pod %s in namespace %s does not have automountServiceAccountToken set to false", [input.review.object.metadata.name, namespace])
        }

        # Helper function to check if a namespace is excluded
        namespace_excluded(namespace, excludedNamespaces) {
          namespace == excludedNamespaces[_]
        }

        # Helper function to allow exceptions for specific pods
        allowed_pod(labels, annotations) {
          labels["allow-automount-sa-token"] == "true"
        }
