apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-app
  labels:
    app: publisher-app
    environment: {{ .Values.publisher.env }}
    {{- include "publisher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: publisher-app
      {{- include "publisher.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: publisher-app
        environment: {{ .Values.publisher.env }}
        {{- include "publisher.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.publisher.app.image.imagePullSecrets }}
      containers:
      - args:
        - bin/rails
        - app:web:start
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.publisher.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: publisher-app
        - configMapRef:
            name: publisher-app
        image: {{ .Values.publisher.app.image.repository }}:{{ .Values.publisher.app.image.tag }}
        imagePullPolicy: Always
        name: publisher-app
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources: {{- toYaml .Values.publisher.app.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL            
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /persistent-storage
          name: persistent-storage
        - mountPath: /tmp
          name: tmp
        - mountPath: /app/tmp
          name: app-tmp
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: publisher-app
      - name: app-tmp
        emptyDir: {}
      - name: tmp
        emptyDir: {}



Invalid YAML - YAMLException: missed comma between flow collection entries at line 8, column 5:
{{- include "publisher.labels" . | ...





Akhil Kurella
  3:26 PM
What was the reason you said? for not going with the /app/tmp mounting?


Govind Bajaj
  3:26 PM
Why should we do it, when /app is workdir ?



/app exists and is owned by USER 1000 because of the WORKDIR and chown commands in the Dockerfile.
However, because readOnlyRootFilesystem: true is set, the entire filesystem (including /app) is mounted as read-only.
When the application tries to write to /app/tmp, it fails with the error
